version: "3"

services:
  mongo-db:
    image: mongo:4.4.7
    hostname: mongo-db
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGOUSERNAME}" # Define the mongoDB user name
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGOPASSWORD}" # Define passwords for security measures within docker
      - "MONGO_INITDB_DATABASE=admin"
    volumes:
      - mongo-db:/data

  postgres-db:
    image: postgres:13.3
    hostname: postgres-db
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGREPASSWORD}"
      - "POSTGRES_USER=${POSTGREUSER}"
      - "POSTGRES_DB=postgres"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  orion:
    image: fiware/orion:3.1.0
    depends_on:
      - mongo-db
    environment:
      - "ORION_MONGO_HOST=mongo-db:27017"
      - "ORION_MONGO_USER=${MONGOUSERNAME}" # Define the mongoDB user name
      - "ORION_MONGO_PASSWORD=${MONGOPASSWORD}" # Define passwords for security measures within docker
      - "ORION_MONGO_AUTH_SOURCE=admin"
      - "ORION_PORT=1026"
    ports:
      - "1026:1026"
    networks:
      - default

  cygnus:
    image: fiware/cygnus-ngsi:2.11.0
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
      - default
    depends_on:
      - postgres-db
    ports:
      - "5055:5055"
      - "5080:5080"
    environment:
      - "CYGNUS_POSTGRESQL_HOST=postgres-db" # Hostname of the PostgreSQL server used to persist historical context data
      - "CYGNUS_POSTGRESQL_PORT=5432" # Port that the PostgreSQL server uses to listen to commands
      - "CYGNUS_POSTGRESQL_USER=${POSTGREUSER}" # Username for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_PASS=${POSTGREPASSWORD}" # Password for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_ENABLE_CACHE=true" # Switch to enable caching within the PostgreSQL configuration
      - "CYGNUS_POSTGRESQL_SERVICE_PORT=5055" # The port the agent.conf is configured for
      - "CYGNUS_LOG_LEVEL=DEBUG" # The logging level for Cygnus
      - "CYGNUS_SERVICE_PORT=5055" # Notification Port that Cygnus listens to for Postgres subscriptions
      - "CYGNUS_API_PORT=5080" # Port that Cygnus listens on for operational reasons

volumes:
  mongo-db: ~
  postgres-db: ~
