name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      - name: npm install for backend
        run: npm --prefix ./StarSeeker/backend install ./StarSeeker/backend --legacy-peer-deps
      - name: npm install for frontend
        run: npm --prefix ./StarSeeker/frontend install ./StarSeeker/frontend --legacy-peer-deps
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,js}'
      - name: Run eslint for backend
        run: npm run lint --prefix ./StarSeeker/backend
      - name: Run test for backend
        run: npm run test --prefix ./StarSeeker/backend
      - name: Run eslint for frontend
        run: npm run lint --prefix ./StarSeeker/frontend
      - name: Run test for frontend
        run: npm run test --prefix ./StarSeeker/frontend
