version: "3"

services:
  starseeker_op:
    image: python:buster
    hostname: op
    container_name: op
    tty: true
    working_dir: /work
    command: >
      sh -c "
      apt install libpq-dev -y &&
      pip3 install . &&
      python3"
    environment:
      - "DSN=postgresql://${POSTGREUSER}:${POSTGREPASSWORD}@postgres:5432/postgres"
      - "BROKER=http://orion:1026/v2/entities"
    volumes:
      - ./work:/work
    networks:
      - starseeker_nw

networks:
  starseeker_nw:
    external: true
    
